# Config Server (optionnel : si Config Server tourne sur 8888, la config centralisée est chargée)
spring.config.import=optional:configserver:http://localhost:8888

spring.application.name=GATEWAY
server.port=8050


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

gateway.service.user=USER
gateway.service.evaluation=EVALUATION
gateway.service.formation=FORMATION
gateway.service.skill=SKILL
gateway.service.project=PROJECT

# Plus de page Whitelabel : erreurs en JSON
server.error.whitelabel.enabled=false