spring.application.name=GATEWAY
server.port=8050

# ============================
# EUREKA (pour lb://)
# ============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# ============================
# ROUTES LB – noms des services Eureka (lb://...)
# ============================
gateway.service.evaluation=EVALUATION
gateway.service.formation=FORMATION

# Plus de page Whitelabel : erreurs en JSON
server.error.whitelabel.enabled=false