<<<<<<< HEAD
# Configuration spécifique à l'API Gateway
spring.application.name=ApiGateway
server.port=8086

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

user.service.uri=lb://USER
skill.service.uri=lb://SKILL
project.service.uri=lb://PROJECT
formation.service.uri=lb://FORMATION

spring.codec.max-in-memory-size=10MB
=======
# API Gateway (spring.application.name=ApiGateway)
spring.application.name=ApiGateway
server.port=8086

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.codec.max-in-memory-size=10MB
>>>>>>> 8d5250d (Ajout du projet MatchFreelance)
