package com.freelancing.contract.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.freelancing.contract.client.OllamaChatClient;
import com.freelancing.contract.config.ContractAiProperties;
import com.freelancing.contract.dto.ContractAiBriefingDTO;
import com.freelancing.contract.dto.ContractHealthDTO;
import com.freelancing.contract.dto.FinancialSummaryDTO;
import com.freelancing.contract.dto.MessageResponseDTO;
import com.freelancing.contract.entity.Contract;
import com.freelancing.contract.repository.ContractRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
@Service
@RequiredArgsConstructor
public class ContractAiBriefingService {

    public static final String DISCLAIMER =
            "This briefing is generated by a local AI model for informational purposes only. "
                    + "It is not legal, financial, or contractual advice. Verify all facts against the contract and messages.";

    private static final String SYSTEM_PROMPT = """
            You are an assistant helping clients evaluate their freelancer's communication and professionalism.
            You receive JSON with contract facts, platform-computed health/financial metrics, and recent chat messages.
            Respond with ONLY valid JSON (no markdown) matching this exact schema:
            {
            "summary": "2-4 sentences in plain language",
            "timelineRisk": "short phrase e.g. on track, at risk, overdue, unknown",
            "chatTone": "1-2 short sentences analyzing the FREELANCER's communication style for the CLIENT to understand. Describe how the freelancer communicates: Are they responsive and professional? Do they provide clear updates? How do they handle feedback or requests? Are they proactive or reactive? Do they communicate respectfully? Examples: Freelancer is responsive and provides clear, detailed updates proactively | Freelancer tends to be brief and reactive, responds when prompted but rarely initiates updates | Freelancer communicates professionally but can be defensive when receiving critical feedback | Excellent communicator, proactive with status updates and handles concerns constructively | Communication is inconsistent, sometimes professional but occasionally dismissive or curt",
            "suggestedNextSteps": ["step1","step2","step3"]
            }
            Rules: suggestedNextSteps must have exactly 3 concise actionable items. Do not invent amounts or dates not in the input.
            If data is insufficient, say so in summary and use conservative wording.
            For chatTone: Always describe the FREELANCER's communication patterns to help the CLIENT understand their working style.
            """;

    private final ContractRepository contractRepository;
    private final ContractHealthService contractHealthService;
    private final ContractFinancialService contractFinancialService;
    private final MessageService messageService;
    private final OllamaChatClient ollamaChatClient;
    private final ContractAiProperties contractAiProperties;
    private final ObjectMapper objectMapper;

    @Transactional(readOnly = true)
    public ContractAiBriefingDTO buildBriefing(Long contractId, Long viewerFreelancerId, Long viewerClientId) {
        boolean hasFreelancer = viewerFreelancerId != null;
        boolean hasClient = viewerClientId != null;
        if (hasFreelancer == hasClient) {
            throw new ResponseStatusException(
                    HttpStatus.BAD_REQUEST, "Provide exactly one of viewerFreelancerId or viewerClientId");
        }

        Contract contract = contractRepository
                .findById(contractId)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Contract not found"));

        if (hasFreelancer) {
            if (!contract.getFreelancerId().equals(viewerFreelancerId)) {
                throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Not your contract");
            }
        } else {
            if (!contract.getClientId().equals(viewerClientId)) {
                throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Not your contract");
            }
        }

        if (!contractAiProperties.getOllama().isEnabled()) {
            throw new ResponseStatusException(
                    HttpStatus.SERVICE_UNAVAILABLE,
                    "Contract AI briefing is disabled. Set contract.ai.ollama.enabled=true and run Ollama locally.");
        }

        ContractHealthDTO health = contractHealthService.getContractHealth(contractId);
        FinancialSummaryDTO financial = contractFinancialService.getFinancialSummary(contractId);
        List<MessageResponseDTO> allMessages = messageService.getMessagesByContractId(contractId);
        ContractAiProperties.Ollama lim = contractAiProperties.getOllama();
        int max = Math.max(1, lim.getMaxMessages());
        List<MessageResponseDTO> tail =
                allMessages.size() <= max ? allMessages : allMessages.subList(allMessages.size() - max, allMessages.size());

        String userJson = buildContextJson(contract, health, financial, tail, viewerFreelancerId, viewerClientId, lim.getMaxCharsPerMessage());

        try {
            String rawJson = ollamaChatClient.chatJson(SYSTEM_PROMPT, userJson);
            ContractAiBriefingDTO dto = parseAndEnrich(contractId, rawJson, lim.getModel(), false);
            dto.setChatTone(augmentChatToneIfAggressiveContent(tail, dto.getChatTone()));
            return dto;
        } catch (Exception e) {
            return heuristicBriefing(contract, health, financial, contractId, lim.getModel(), tail);
        }
    }

    private String buildContextJson(
            Contract contract,
            ContractHealthDTO health,
            FinancialSummaryDTO financial,
            List<MessageResponseDTO> messages,
            Long viewerFreelancerId,
            Long viewerClientId,
            int maxChars) {
        ObjectNode root = objectMapper.createObjectNode();
        root.put("viewerRole", viewerFreelancerId != null ? "FREELANCER" : "CLIENT");
        root.put(
                "chatToneReminder",
                "For field chatTone: Analyze the FREELANCER's messages to help the CLIENT understand their communication style. "
                        + "Describe: responsiveness, clarity, professionalism, whether they're proactive with updates, "
                        + "and how they handle feedback. Focus only on the freelancer's behavior, not the client's.");
        ObjectNode c = root.putObject("contract");
        c.put("id", contract.getId());
        c.put("projectId", contract.getProjectId());
        c.put("status", contract.getStatus() != null ? contract.getStatus().name() : "");
        c.put("progressPercent", contract.getProgressPercent() != null ? contract.getProgressPercent() : 0);
        c.put("termsExcerpt", truncate(contract.getTerms(), maxChars));
        c.put("applicationMessageExcerpt", truncate(contract.getApplicationMessage(), maxChars));
        if (contract.getStartDate() != null) {
            c.put("startDate", dateToIsoInstantString(contract.getStartDate()));
        }
        if (contract.getEndDate() != null) {
            c.put("endDate", dateToIsoInstantString(contract.getEndDate()));
        }

        ObjectNode h = root.putObject("platformHealth");
        h.put("healthScore", health.getHealthScore());
        h.put("healthLevel", health.getHealthLevel());
        h.put("timelineStatus", health.getTimelineStatus() != null ? health.getTimelineStatus() : "");
        if (health.getProgressVsExpectedRatio() != null) {
            h.put("progressVsExpectedRatio", health.getProgressVsExpectedRatio());
        }
        ArrayNode flags = h.putArray("flags");
        if (health.getFlags() != null) {
            health.getFlags().forEach(flags::add);
        }

        ObjectNode f = root.putObject("platformFinancial");
        f.put("totalContractValue", financial.getTotalContractValue() != null ? financial.getTotalContractValue() : 0);
        f.put("freelancerNetAmount", financial.getFreelancerNetAmount() != null ? financial.getFreelancerNetAmount() : 0);
        f.put("amountReleasableByProgress", financial.getAmountReleasableByProgress() != null
                ? financial.getAmountReleasableByProgress()
                : 0);
        f.put("platformFeePercent", financial.getPlatformFeePercent() != null ? financial.getPlatformFeePercent() : 0);

        ArrayNode arr = root.putArray("recentMessagesChronological");
        Long fid = contract.getFreelancerId();
        Long cid = contract.getClientId();
        for (MessageResponseDTO m : messages) {
            ObjectNode msg = arr.addObject();
            msg.put("senderRole", m.getSenderId() != null && m.getSenderId().equals(fid) ? "FREELANCER" : "CLIENT");
            msg.put("content", truncate(m.getContent(), maxChars));
            if (m.getCreatedAt() != null) {
                msg.put("createdAt", dateToIsoInstantString(m.getCreatedAt()));
            }
        }

        try {
            return objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(root);
        } catch (JsonProcessingException e) {
            throw new IllegalStateException(e);
        }
    }

    /** Safe for {@code java.sql.Date} from JPA DATE columns ({@code Date.toInstant()} is unsupported there). */
    private static String dateToIsoInstantString(Date d) {
        return Instant.ofEpochMilli(d.getTime()).toString();
    }

    private static String truncate(String s, int maxChars) {
        if (s == null) {
            return "";
        }
        if (s.length() <= maxChars) {
            return s;
        }
        return s.substring(0, maxChars) + "…";
    }

    /**
     * Small models sometimes miss hostility. If message text matches likely aggressive wording but chatTone does not
     * acknowledge conflict/aggression, append a factual note.
     */
    private static String augmentChatToneIfAggressiveContent(List<MessageResponseDTO> messages, String chatTone) {
        if (messages == null || messages.isEmpty()) {
            return chatTone != null ? chatTone : "";
        }
        String combined =
                messages.stream()
                        .map(MessageResponseDTO::getContent)
                        .filter(Objects::nonNull)
                        .collect(Collectors.joining("\n"));
        if (combined.isBlank()) {
            return chatTone != null ? chatTone : "";
        }
        if (!LIKELY_AGGRESSIVE_MESSAGE.matcher(combined).find()) {
            return chatTone != null ? chatTone : "";
        }
        String tone = chatTone != null ? chatTone : "";
        if (TONE_ACKNOWLEDGES_AGGRESSION.matcher(tone).find()) {
            return tone;
        }
        String note =
                " Recent messages contain wording that may be hostile, insulting, or strongly confrontational; "
                        + "review the thread and consider de-escalation or clarification.";
        return tone.isBlank() ? note.trim() : tone + note;
    }

    /** Heuristic: insults, threats, strong profanity directed at person, legal threats — EN/FR snippets common in chat. */
    private static final Pattern LIKELY_AGGRESSIVE_MESSAGE =
            Pattern.compile(
                    "(\\b(stupid|idiot|idiotic|pathetic|useless|incompetent|moron|damn\\s*you|screw\\s*you|f+\\s*u+|"
                            + "shut\\s+up|go\\s+to\\s+hell|kill\\s+yourself|lawsuit|sue\\s+you|i('ll|\\s+will)\\s+sue|"
                            + "how\\s+dare|piece\\s+of\\s+sh|"
                            + "threat|threatening)\\b)|"
                            + "(\\b(imbécile|débile|connard|connasse|nul(le)?|ferme\\s+la|va\\s+te\\s+f|merde)\\b)",
                    Pattern.CASE_INSENSITIVE | Pattern.UNICODE_CHARACTER_CLASS);

    private static final Pattern TONE_ACKNOWLEDGES_AGGRESSION =
            Pattern.compile(
                    "aggress|hostile|threat|insult|confrontation|harsh(?!ware)|rud(e|eness)|demean|angry|harass|toxic|"
                            + "combative|combattif|insultant|menace|hostile|violent",
                    Pattern.CASE_INSENSITIVE);

    private ContractAiBriefingDTO parseAndEnrich(Long contractId, String rawJson, String model, boolean fallback) {
        try {
            JsonNode node = objectMapper.readTree(rawJson);
            String summary = textOrEmpty(node, "summary");
            String timelineRisk = textOrEmpty(node, "timelineRisk");
            String chatTone = textOrEmpty(node, "chatTone");
            List<String> steps = new ArrayList<>();
            JsonNode arr = node.get("suggestedNextSteps");
            if (arr != null && arr.isArray()) {
                arr.forEach(n -> steps.add(n.asText("")));
            }
            padSteps(steps);
            return ContractAiBriefingDTO.builder()
                    .contractId(contractId)
                    .summary(summary)
                    .timelineRisk(timelineRisk)
                    .chatTone(chatTone)
                    .suggestedNextSteps(steps.subList(0, 3))
                    .disclaimer(DISCLAIMER)
                    .model(model)
                    .generatedAt(Instant.now())
                    .fallback(fallback)
                    .build();
        } catch (Exception e) {
            throw new IllegalStateException("Invalid JSON from model: " + e.getMessage(), e);
        }
    }

    private static void padSteps(List<String> steps) {
        while (steps.size() < 3) {
            steps.add("Review contract terms and latest messages in the app.");
        }
        while (steps.size() > 3) {
            steps.remove(steps.size() - 1);
        }
    }

    private static String textOrEmpty(JsonNode node, String field) {
        JsonNode n = node.get(field);
        return n == null || n.isNull() ? "" : n.asText("").trim();
    }

    private ContractAiBriefingDTO heuristicBriefing(
            Contract contract,
            ContractHealthDTO health,
            FinancialSummaryDTO financial,
            Long contractId,
            String model,
            List<MessageResponseDTO> messages) {
        String summary =
                String.format(
                        "Contract #%d is %s. Platform health score: %d (%s). Timeline: %s.",
                        contractId,
                        contract.getStatus() != null ? contract.getStatus().name() : "UNKNOWN",
                        health.getHealthScore(),
                        health.getHealthLevel() != null ? health.getHealthLevel() : "N/A",
                        health.getTimelineStatus() != null ? health.getTimelineStatus() : "UNKNOWN");
        String risk =
                health.getHealthScore() >= 70 ? "lower concern" : health.getHealthScore() >= 40 ? "moderate concern" : "elevated concern";
        List<String> steps = new ArrayList<>();
        steps.add("Confirm next deliverable and deadline in chat with the other party.");
        if (health.getFlags() != null && health.getFlags().stream().anyMatch(s -> s.contains("EXTRA"))) {
            steps.add("Resolve any pending extra-budget request in the contract view.");
        } else {
            steps.add("Align progress updates with the agreed timeline.");
        }
        steps.add(
                String.format(
                        "Review financial summary: total %.2f TND, releasable by progress: %.2f TND.",
                        financial.getTotalContractValue() != null ? financial.getTotalContractValue() : 0.0,
                        financial.getAmountReleasableByProgress() != null ? financial.getAmountReleasableByProgress() : 0.0));
        padSteps(steps);
        String tone = augmentChatToneIfAggressiveContent(messages, "not analyzed (model unavailable)");
        return ContractAiBriefingDTO.builder()
                .contractId(contractId)
                .summary(summary)
                .timelineRisk(risk)
                .chatTone(tone)
                .suggestedNextSteps(steps.subList(0, 3))
                .disclaimer(DISCLAIMER)
                .model(model + " (heuristic fallback)")
                .generatedAt(Instant.now())
                .fallback(true)
                .build();
    }
}
