package com.freelancing.contract.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.freelancing.contract.client.OllamaChatClient;
import com.freelancing.contract.config.ContractAiProperties;
import com.freelancing.contract.dto.ContractHealthDTO;
import com.freelancing.contract.dto.ExtraBudgetAiAnalysisDTO;
import com.freelancing.contract.dto.FinancialSummaryDTO;
import com.freelancing.contract.dto.ProposeExtraBudgetRequestDTO;
import com.freelancing.contract.entity.Contract;
import com.freelancing.contract.enums.ContractStatus;
import com.freelancing.contract.repository.ContractRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

@Service
@RequiredArgsConstructor
public class ExtraBudgetAiAnalysisService {

    public static final String DISCLAIMER =
            "This analysis is generated by a local AI model for discussion only. "
                    + "It is not legal, financial, or contractual advice. "
                    + "Verify amounts and scope with the client and your written agreement.";

    private static final String SYSTEM_PROMPT =
            """
            You help freelancers think through an extra-budget request before they send it to the client.
            You receive JSON with contract facts, platform financial and health metrics, and the freelancer's proposed extra amount and reason.
            Respond with ONLY valid JSON (no markdown) matching this exact schema:
            {
              "needAssessment": "NEEDED" | "QUESTIONABLE" | "UNCLEAR",
              "needRationale": "2-4 sentences: is the extra work or cost plausibly justified given scope and progress?",
              "priceAssessment": "BELOW_MARKET" | "FAIR" | "HIGH" | "UNCLEAR",
              "priceRationale": "1-3 sentences comparing the proposed amount to existing budgets and typical expectations (qualitative)",
              "projectFit": "ALIGNED" | "NEUTRAL" | "MISALIGNED" | "UNCLEAR",
              "projectFitRationale": "1-3 sentences: does this support the stated project goals and timeline?",
              "risksOrConcerns": ["short bullet 1", "short bullet 2"],
              "negotiationTips": ["tip1", "tip2", "tip3"],
              "overallSummary": "2-4 sentences: balanced takeaway for the freelancer (informational only)"
            }
            Rules: risksOrConcerns must have 2-4 items; negotiationTips must have exactly 3 concise items.
            If the reason is empty or vague, set needAssessment to UNCLEAR and say more detail is needed.
            Do not invent specific legal clauses or exact market rates not implied by the input.
            """;

    private final ContractRepository contractRepository;
    private final ContractFinancialService contractFinancialService;
    private final ContractHealthService contractHealthService;
    private final OllamaChatClient ollamaChatClient;
    private final ContractAiProperties contractAiProperties;
    private final ObjectMapper objectMapper;

    @Transactional(readOnly = true)
    public ExtraBudgetAiAnalysisDTO analyze(Long contractId, ProposeExtraBudgetRequestDTO request) {
        if (!contractAiProperties.getOllama().isEnabled()) {
            throw new ResponseStatusException(
                    HttpStatus.SERVICE_UNAVAILABLE,
                    "Contract AI is disabled. Set contract.ai.ollama.enabled=true and run Ollama locally.");
        }
        Contract contract =
                contractRepository.findById(contractId).orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Contract not found"));
        if (!contract.getFreelancerId().equals(request.getFreelancerId())) {
            throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Only the freelancer on this contract can request this analysis");
        }
        if (contract.getStatus() != ContractStatus.ACTIVE) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Extra-budget analysis is only available for ACTIVE contracts");
        }
        Double amount = request.getAmount();
        if (amount == null || amount <= 0) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Amount must be positive");
        }

        ContractHealthDTO health = contractHealthService.getContractHealth(contractId);
        FinancialSummaryDTO financial = contractFinancialService.getFinancialSummary(contractId);
        int maxChars = Math.max(400, contractAiProperties.getOllama().getMaxCharsPerMessage() * 2);

        String userJson = buildContextJson(contract, health, financial, amount, request.getReason(), maxChars);
        String model = contractAiProperties.getOllama().getModel();
        try {
            String rawJson = ollamaChatClient.chatJson(SYSTEM_PROMPT, userJson);
            return parseAndEnrich(contractId, rawJson, model, false);
        } catch (Exception e) {
            return heuristicAnalysis(contractId, contract, health, financial, amount, request.getReason(), model);
        }
    }

    private String buildContextJson(
            Contract contract,
            ContractHealthDTO health,
            FinancialSummaryDTO financial,
            double proposedAmount,
            String reason,
            int maxChars) {
        ObjectNode root = objectMapper.createObjectNode();
        root.put("contractId", contract.getId());
        root.put("projectId", contract.getProjectId());
        root.put("status", contract.getStatus() != null ? contract.getStatus().name() : "");
        root.put("progressPercent", contract.getProgressPercent() != null ? contract.getProgressPercent() : 0);
        root.put("proposedBudgetOriginal", contract.getProposedBudget() != null ? contract.getProposedBudget() : 0);
        root.put("extraTasksBudgetAlreadyAllocated", contract.getExtraTasksBudget() != null ? contract.getExtraTasksBudget() : 0);
        root.put("termsExcerpt", truncate(contract.getTerms(), maxChars));
        root.put("applicationMessageExcerpt", truncate(contract.getApplicationMessage(), maxChars));
        root.put("proposedExtraAmount", proposedAmount);
        root.put("proposedExtraReason", truncate(reason != null ? reason : "", maxChars));

        ObjectNode h = root.putObject("platformHealth");
        h.put("healthScore", health.getHealthScore());
        h.put("healthLevel", health.getHealthLevel() != null ? health.getHealthLevel() : "");
        h.put("timelineStatus", health.getTimelineStatus() != null ? health.getTimelineStatus() : "");
        ArrayNode flags = h.putArray("flags");
        if (health.getFlags() != null) {
            health.getFlags().forEach(flags::add);
        }

        ObjectNode f = root.putObject("platformFinancial");
        f.put("baseBudget", financial.getBaseBudget() != null ? financial.getBaseBudget() : 0);
        f.put("extraTasksBudget", financial.getExtraTasksBudget() != null ? financial.getExtraTasksBudget() : 0);
        f.put("totalContractValue", financial.getTotalContractValue() != null ? financial.getTotalContractValue() : 0);
        f.put("amountReleasableByProgress", financial.getAmountReleasableByProgress() != null ? financial.getAmountReleasableByProgress() : 0);

        try {
            return objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(root);
        } catch (Exception e) {
            throw new IllegalStateException(e);
        }
    }

    private ExtraBudgetAiAnalysisDTO parseAndEnrich(Long contractId, String rawJson, String model, boolean fallback) {
        try {
            JsonNode node = objectMapper.readTree(rawJson);
            List<String> risks = readStringList(node.get("risksOrConcerns"), 4);
            while (risks.size() < 2) {
                risks.add("Clarify scope and acceptance criteria with the client before finalizing the amount.");
            }
            if (risks.size() > 4) {
                risks = risks.subList(0, 4);
            }
            List<String> tips = readStringList(node.get("negotiationTips"), 10);
            while (tips.size() < 3) {
                tips.add("Document what is included in the extra budget and the delivery date.");
            }
            tips = tips.subList(0, 3);

            return ExtraBudgetAiAnalysisDTO.builder()
                    .contractId(contractId)
                    .needAssessment(normalizeEnum(textOrEmpty(node, "needAssessment"), "UNCLEAR", "NEEDED", "QUESTIONABLE", "UNCLEAR"))
                    .needRationale(textOrEmpty(node, "needRationale"))
                    .priceAssessment(normalizeEnum(
                            textOrEmpty(node, "priceAssessment"), "UNCLEAR", "BELOW_MARKET", "FAIR", "HIGH", "UNCLEAR"))
                    .priceRationale(textOrEmpty(node, "priceRationale"))
                    .projectFit(normalizeEnum(
                            textOrEmpty(node, "projectFit"), "UNCLEAR", "ALIGNED", "NEUTRAL", "MISALIGNED", "UNCLEAR"))
                    .projectFitRationale(textOrEmpty(node, "projectFitRationale"))
                    .risksOrConcerns(risks)
                    .negotiationTips(tips)
                    .overallSummary(textOrEmpty(node, "overallSummary"))
                    .disclaimer(DISCLAIMER)
                    .model(model)
                    .generatedAt(Instant.now())
                    .fallback(fallback)
                    .build();
        } catch (Exception e) {
            throw new IllegalStateException("Invalid JSON from model: " + e.getMessage(), e);
        }
    }

    private static String normalizeEnum(String raw, String defaultVal, String... allowed) {
        if (raw == null || raw.isBlank()) {
            return defaultVal;
        }
        String u = raw.trim().toUpperCase().replace(" ", "_");
        for (String a : allowed) {
            if (a.equals(u)) {
                return a;
            }
        }
        return defaultVal;
    }

    private static List<String> readStringList(JsonNode arr, int maxItems) {
        List<String> out = new ArrayList<>();
        if (arr != null && arr.isArray()) {
            arr.forEach(n -> {
                if (out.size() < maxItems) {
                    String s = n.asText("").trim();
                    if (!s.isEmpty()) {
                        out.add(s);
                    }
                }
            });
        }
        return out;
    }

    private static String textOrEmpty(JsonNode node, String field) {
        JsonNode n = node.get(field);
        return n == null || n.isNull() ? "" : n.asText("").trim();
    }

    private static String truncate(String s, int maxChars) {
        if (s == null) {
            return "";
        }
        if (s.length() <= maxChars) {
            return s;
        }
        return s.substring(0, maxChars) + "…";
    }

    private ExtraBudgetAiAnalysisDTO heuristicAnalysis(
            Long contractId,
            Contract contract,
            ContractHealthDTO health,
            FinancialSummaryDTO financial,
            double proposedAmount,
            String reason,
            String model) {
        double total = financial.getTotalContractValue() != null ? financial.getTotalContractValue() : 0;
        double ratio = total > 0 ? proposedAmount / total : 0;
        String need = (reason == null || reason.isBlank()) ? "UNCLEAR" : (ratio > 0.5 ? "QUESTIONABLE" : "NEEDED");
        String price = ratio <= 0.1 ? "FAIR" : ratio <= 0.25 ? "HIGH" : "UNCLEAR";
        if (total <= 0) {
            price = "UNCLEAR";
        }
        String fit = health.getHealthScore() >= 60 ? "ALIGNED" : "NEUTRAL";
        List<String> risks = new ArrayList<>();
        risks.add("Automated fallback: compare the requested amount to the current total contract value.");
        if (reason == null || reason.isBlank()) {
            risks.add("Add a clear reason so the client can assess scope and value.");
        } else {
            risks.add("Confirm the extra work is outside the original agreed scope.");
        }
        List<String> tips = new ArrayList<>();
        tips.add("Break down what the extra budget covers (deliverables, revisions, timeline).");
        tips.add("Reference progress (" + (contract.getProgressPercent() != null ? contract.getProgressPercent() : 0) + "%) and remaining work.");
        tips.add("Offer a smaller optional package if the client pushes back on price.");

        String summary =
                String.format(
                        "Heuristic only (model unavailable): proposed +%.0f vs total contract ~%.0f (ratio ~%.0f%%). "
                                + "Health score %d (%s). Use AI when Ollama is running for a richer review.",
                        proposedAmount,
                        total,
                        ratio * 100,
                        health.getHealthScore(),
                        health.getHealthLevel() != null ? health.getHealthLevel() : "n/a");

        return ExtraBudgetAiAnalysisDTO.builder()
                .contractId(contractId)
                .needAssessment(need)
                .needRationale(
                        (reason == null || reason.isBlank())
                                ? "Reason not provided; the client may reject without context."
                                : "Rough heuristic: non-empty reason provided; validate against original scope.")
                .priceAssessment(price)
                .priceRationale(
                        total > 0
                                ? String.format("Proposed amount is about %.0f%% of current total contract value (rule-of-thumb only).", ratio * 100)
                                : "Total contract value unknown; price judgment deferred.")
                .projectFit(fit)
                .projectFitRationale("Based only on platform health score and progress snapshot.")
                .risksOrConcerns(risks)
                .negotiationTips(tips)
                .overallSummary(summary)
                .disclaimer(DISCLAIMER)
                .model(model + " (heuristic fallback)")
                .generatedAt(Instant.now())
                .fallback(true)
                .build();
    }
}
