apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  # Database Configuration
  MYSQL_HOST: "mysql-service"
  MYSQL_PORT: "3306"
  MYSQL_ROOT_PASSWORD: "pidev"
  
  # Eureka Configuration
  EUREKA_HOST: "eureka-service"
  EUREKA_PORT: "8761"
  EUREKA_URL: "http://eureka-service:8761/eureka/"
  
  # Config Server Configuration
  CONFIG_SERVER_HOST: "config-server"
  CONFIG_SERVER_PORT: "8888"
  
  # Spring Profiles
  SPRING_PROFILES_ACTIVE: "mysql"
  
  # API Gateway Configuration
  GATEWAY_HOST: "gateway-service"
  GATEWAY_PORT: "8081"
