pipeline {
    agent any

    environment {
        IMAGE_NAME = "formation-service"
        IMAGE_TAG = "1.0.${BUILD_NUMBER}"
        SONAR_HOST = "http://sonarqube:9000"
        MODULE_DIR = "backend/microservices/Formation"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/khadijaba/Esprit-PIDEV-4SAE10-2026-MatchFreelance.git'
            }
        }

        stage('Build Maven') {
            steps {
                dir("${MODULE_DIR}") {
                    sh "mvn clean package -DskipTests"
                }
            }
        }

        stage('Test') {
            steps {
                dir("${MODULE_DIR}") {
                    sh "mvn test"
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withCredentials([string(credentialsId: 'sonar-token-backend', variable: 'SONAR_TOKEN')]) {
                    dir("${MODULE_DIR}") {
                        sh """
                        mvn sonar:sonar \
                        -Dsonar.host.url=${SONAR_HOST} \
                        -Dsonar.login=${SONAR_TOKEN}
                        """
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ${MODULE_DIR}"
            }
        }

        stage('Docker Run') {
            steps {
                sh "docker run -d -p 9090:9090 ${IMAGE_NAME}:${IMAGE_TAG}"
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
