apiVersion: v1
kind: Secret
metadata:
  name: skill-mysql-secret
  namespace: __NAMESPACE__
type: Opaque
stringData:
  MYSQL_DATABASE: skilldb
  MYSQL_USER: skill
  MYSQL_PASSWORD: skill123
  MYSQL_ROOT_PASSWORD: root123
