apiVersion: v1
kind: Service
metadata:
  name: formation-ms
  namespace: formation
  labels:
    app.kubernetes.io/name: formation-ms
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: matchfreelance
    app.kubernetes.io/version: "0.0.1"
    app: formation-ms
    env: dev
    team: backend
spec:
  type: ClusterIP
  selector:
    app: formation-ms
  ports:
    - name: http
      port: 8081
      targetPort: 8081
