spring.application.name=eureka
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Cette IP doit être accessible par les autres membres
eureka.instance.hostname=192.168.1.2
eureka.instance.prefer-ip-address=true

