spring.application.name=eureka
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

<<<<<<< HEAD
eureka.instance.hostname= 172.16.2.149
=======



# Docker : définir EUREKA_INSTANCE_HOSTNAME=eureka ; local : localhost par défaut
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
>>>>>>> 8d5250d (Ajout du projet MatchFreelance)
eureka.instance.prefer-ip-address=true


