spring.application.name=eureka
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.instance.hostname= 192.168.1.8
eureka.instance.prefer-ip-address=true


