apiVersion: apps/v1
kind: Deployment
metadata:
  name: formation
  labels:
    app: formation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: formation
  template:
    metadata:
      labels:
        app: formation
    spec:
      containers:
        - name: formation
          image: khadijabenayed/formation:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/FormationDB?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"
          ports:
            - containerPort: 8096
