apiVersion: v1
kind: Service
metadata:
  name: formation
  namespace: formation
  labels:
    app: formation
    env: production
    team: khadijaba
    version: "1.0"
spec:
  selector:
    app: formation
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096
  type: ClusterIP
