import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { ExamenService } from '../../services/examen.service';
import { FormationService } from '../../services/formation.service';
import { ToastService } from '../../services/toast.service';
import { Examen, ExamenDraft, QuestionDto } from '../../models/examen.model';
import { Formation } from '../../models/formation.model';

@Component({
  selector: 'app-examen-list',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './examen-list.component.html',
})
export class ExamenListComponent implements OnInit {
  examens: Examen[] = [];
  formations: Formation[] = [];
  loading = true;
  formationsLoading = false;
  selectedFormationId: number | null = null;
  generating = false;
  confirming = false;
  draftGeneratedExamen: ExamenDraft | null = null;
  /** Active l’appel LLM (Ollama / OpenAI) côté serveur si configuré ; sinon repli heuristique. */
  useLlmForAutoGenerate = true;

  constructor(
    private examenService: ExamenService,
    private formationService: FormationService,
    private toast: ToastService,
    private router: Router
  ) {}

  ngOnInit() {
    this.load();
    this.loadFormations();
  }

  load() {
    this.loading = true;
    this.examenService.getAll().subscribe({
      next: (data) => {
        this.examens = Array.isArray(data) ? data : [];
        this.loading = false;
      },
      error: () => {
        this.loading = false;
        this.toast.error('Impossible de charger les examens');
      },
    });
  }

  loadFormations() {
    this.formationsLoading = true;
    this.formationService.getAll().subscribe({
      next: (list) => {
        this.formations = Array.isArray(list) ? list : [];
        this.formationsLoading = false;
      },
      error: () => {
        this.formationsLoading = false;
        this.toast.error('Impossible de charger les formations pour la génération.');
      },
    });
  }

  generateFromFormation() {
    const id = this.selectedFormationId;
    if (id == null || id < 1) {
      this.toast.error('Choisissez une formation.');
      return;
    }
    this.runPreview(id);
  }

  private runPreview(formationId: number) {
    this.generating = true;
    this.examenService
      .previewGenerateFromFormation(formationId, {
        seuilReussi: 60,
        useLlm: this.useLlmForAutoGenerate,
      })
      .subscribe({
      next: (draft) => {
        this.generating = false;
        this.draftGeneratedExamen = draft;
        this.toast.success('Prévisualisation prête : validez ou régénérez.');
      },
      error: (err) => {
        this.generating = false;
        const msg =
          err.error?.message ??
          err.message ??
          'Échec de la génération (Formation / modules / réseau).';
        this.toast.error(msg);
      },
    });
  }

  closeDraftPreview() {
    this.draftGeneratedExamen = null;
  }

  regenerateDraft() {
    const id = this.selectedFormationId;
    if (id == null || id < 1) return;
    this.runPreview(id);
  }

  confirmDraft() {
    const draft = this.draftGeneratedExamen;
    if (!draft) return;
    this.confirming = true;
    this.examenService.confirmAutoGenerated(draft).subscribe({
      next: (saved) => {
        this.confirming = false;
        this.draftGeneratedExamen = null;
        this.toast.success('Examen enregistré.');
        this.load();
        if (saved.id != null) {
          this.router.navigate(['/admin/examens', saved.id]);
        }
      },
      error: (err) => {
        this.confirming = false;
        this.toast.error(err.error?.message ?? err.message ?? 'Enregistrement impossible.');
      },
    });
  }

  optionLabel(q: QuestionDto, letter: 'A' | 'B' | 'C' | 'D'): string {
    const v =
      letter === 'A' ? q.optionA : letter === 'B' ? q.optionB : letter === 'C' ? q.optionC : q.optionD;
    return v ?? '—';
  }

  onDelete(id: number) {
    if (!confirm('Supprimer cet examen ?')) return;
    this.examenService.delete(id).subscribe({
      next: () => {
        this.toast.success('Examen supprimé');
        this.load();
      },
      error: () => this.toast.error('Erreur lors de la suppression'),
    });
  }
}
