apiVersion: v1
kind: Service
metadata:
  name: project-ms
  namespace: __NAMESPACE__
  labels:
    app: project-ms
spec:
  selector:
    app: project-ms
  ports:
    - name: http
      port: 8084
      targetPort: 8084
  type: ClusterIP
