# Nom Eureka : doit correspondre à lb://PROJECT dans la Gateway
spring.application.name=PROJECT
server.port=8084

# Eureka : même URL pour toute l'équipe (variable pour intégration)
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# base de données
spring.datasource.url=jdbc:mysql://localhost:3306/project?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
