# Bootstrap uniquement — config métier : Config Server → PROJECT.properties
# (même schéma que AWD-Training candidat + Config Server)
spring.application.name=PROJECT
#configServer
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
