# Bootstrap — config : Config Server → FORMATION.properties
spring.application.name=FORMATION
#configServer
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
