# Config Server - port standard
server.port=8888
spring.application.name=CONFIG-SERVER

# Eureka : s'enregistrer pour apparaître sur le tableau de bord (http://localhost:8761)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Dépôt de config (native = classpath)
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config-repo

# Optionnel : si le dossier est dans le JAR (copié dans resources)
# spring.cloud.config.server.native.search-locations=classpath:/config-repo
