apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: formation
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/khadijaba/Esprit-PIDEV-4SAE10-2026-MatchFreelance.git
    targetRevision: douja
    path: backend/microservices/Formation/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
