apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: formation
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-timeout: 900s
  labels:
    app.kubernetes.io/name: formation
    app.kubernetes.io/part-of: match-freelance
    app.kubernetes.io/managed-by: argocd
    team: khadijaba
    env: production
spec:
  project: default
  source:
    repoURL: https://github.com/khadijaba/Esprit-PIDEV-4SAE10-2026-MatchFreelance.git
    targetRevision: douja
    path: backend/microservices/Formation/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: formation
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    automated:
      prune: true
      selfHeal: true
