# kubectl apply -n argocd -f mysql-app.yaml
# (après installation d'Argo CD et création du secret repo si dépôt privé)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-timeout: 600s
spec:
  project: default
  source:
    repoURL: https://github.com/khadijaba/Esprit-PIDEV-4SAE10-2026-MatchFreelance.git
    targetRevision: douja
    path: backend/microservices/k8s
    directory:
      include: mysql.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
