apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation
  namespace: evaluation
  labels:
    app: evaluation
    env: production
    team: khadijaba
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation
  template:
    metadata:
      labels:
        app: evaluation
        env: production
        team: khadijaba
        version: "1.0"
    spec:
      containers:
        - name: evaluation
          image: khadijabenayed/evaluation:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.mysql.svc.cluster.local:3306/EvaluationDB?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"
          ports:
            - containerPort: 8083
