apiVersion: v1
kind: Service
metadata:
  name: evaluation
  labels:
    app: evaluation
spec:
  selector:
    app: evaluation
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
