apiVersion: apps/v1
kind: Deployment
metadata:
  name: productivity-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productivity-service
  template:
    metadata:
      labels:
        app: productivity-service
    spec:
      containers:
      - name: productivity-service
        image: khadijabenayed/productivity:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8087
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "mysql"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://localhost:8761/eureka/"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: productivity-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: productivity-service
  ports:
  - port: 8087
    targetPort: 8087
    nodePort: 30087
