apiVersion: apps/v1
kind: Deployment
metadata:
  name: productivity-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productivity-service
  template:
    metadata:
      labels:
        app: productivity-service
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: productivity-service
        image: benhajdahmenahmed/productivity:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8087
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "mysql"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/productivity?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "pidev"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-service:8761/eureka/"
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: productivity-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: productivity-service
  ports:
  - port: 8087
    targetPort: 8087
